=== susmeenagit/xml-lab/lab xml/college.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="college">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="student" minOccurs="1" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="name" type="xsd:string"/>
              <xsd:element name="address" type="xsd:string"/>
              <xsd:element name="phone" type="xsd:string"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="subject" minOccurs="0" maxOccurs="unbounded">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:enumeration value="BCA"/>
              <xsd:enumeration value="BIT"/>
              <xsd:enumeration value="MIT"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== susmeenagit/xml-lab/lab xml/college.xml
<?xml version="1.0" encoding="UTF-8"?>
<college xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="college.xsd">

    <student>
        <name>Akriti Niroula</name>
        <address>Belbari</address>
        <phone>980671234</phone>
    </student>
    
    <student>
        <name>Parina Bhujel</name>
        <address>Itahri</address>
        <phone>9845675678</phone>
    </student>
    
    <subject>BCA</subject>
    <subject>BIT</subject>
    <subject>MIT</subject>
    
</college>
